version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10.15.3
jobs:
  build:
    executor: node
    steps:
      - checkout
      - run:
          name: package install
          command: npm install
      - run:
          name: Echo
          command: echo "CI is fire."
      - run:
          name: Test
          command: npm run test

workflows:
  version: 2
  sample:
    jobs:
      - build
